COMPANIES = [
    # RAN / Core Vendors
    {"name": "Ericsson", "segment": "RAN Vendor", "hq_country": "SE", "hq_city": "Stockholm",
     "founded_year": 1876, "employee_count": 95000, "revenue_usd_bn": 24.5, "revenue_year": 2023,
     "ticker": "ERIC", "public": True, "website": "https://www.ericsson.com",
     "description": "Swedish multinational networking and telecommunications company, global leader in 5G RAN equipment."},
    {"name": "Nokia", "segment": "RAN Vendor", "hq_country": "FI", "hq_city": "Espoo",
     "founded_year": 1865, "employee_count": 86000, "revenue_usd_bn": 22.3, "revenue_year": 2023,
     "ticker": "NOK", "public": True, "website": "https://www.nokia.com",
     "description": "Finnish multinational telecommunications and technology company providing end-to-end 5G network solutions."},
    {"name": "Huawei", "segment": "RAN Vendor", "hq_country": "CN", "hq_city": "Shenzhen",
     "founded_year": 1987, "employee_count": 207000, "revenue_usd_bn": 99.5, "revenue_year": 2023,
     "public": False, "website": "https://www.huawei.com",
     "description": "Chinese multinational technology corporation and world's largest telecom equipment manufacturer."},
    {"name": "ZTE", "segment": "RAN Vendor", "hq_country": "CN", "hq_city": "Shenzhen",
     "founded_year": 1985, "employee_count": 75000, "revenue_usd_bn": 16.8, "revenue_year": 2023,
     "ticker": "000063.SZ", "public": True, "website": "https://www.zte.com.cn",
     "description": "Chinese multinational telecommunications equipment and systems company."},
    {"name": "Samsung Networks", "segment": "RAN Vendor", "hq_country": "KR", "hq_city": "Seoul",
     "founded_year": 2012, "employee_count": 270000, "revenue_usd_bn": 5.2, "revenue_year": 2023,
     "public": False, "website": "https://networks.samsung.com",
     "description": "Samsung's telecom network division providing 5G RAN and core network solutions."},
    {"name": "Mavenir", "segment": "RAN Vendor", "hq_country": "US", "hq_city": "Richardson",
     "founded_year": 2005, "employee_count": 5000, "public": False,
     "website": "https://mavenir.com",
     "description": "Cloud-native network software company and Open RAN pioneer providing vRAN and 5G core solutions."},
    {"name": "Parallel Wireless", "segment": "RAN Vendor", "hq_country": "US", "hq_city": "Nashua",
     "founded_year": 2012, "employee_count": 500, "public": False,
     "website": "https://www.parallelwireless.com",
     "description": "Open RAN software company providing cloud-native all-G (2G/3G/4G/5G) solutions."},
    {"name": "Rakuten Symphony", "segment": "RAN Vendor", "hq_country": "JP", "hq_city": "Tokyo",
     "founded_year": 2021, "public": False, "website": "https://symphony.rakuten.com",
     "description": "Rakuten's telecom software subsidiary offering cloud-native Open RAN and network automation."},

    # Transport Vendors
    {"name": "Ciena", "segment": "Transport Vendor", "hq_country": "US", "hq_city": "Hanover",
     "founded_year": 1992, "employee_count": 8300, "revenue_usd_bn": 3.9, "revenue_year": 2023,
     "ticker": "CIEN", "public": True, "website": "https://www.ciena.com",
     "description": "American networking equipment and software company specializing in coherent optical transport."},
    {"name": "Infinera", "segment": "Transport Vendor", "hq_country": "US", "hq_city": "San Jose",
     "founded_year": 2000, "employee_count": 3500, "revenue_usd_bn": 1.8, "revenue_year": 2023,
     "ticker": "INFN", "public": True, "website": "https://www.infinera.com",
     "description": "Optical networking equipment provider specializing in intelligent transport networks."},
    {"name": "ADTRAN", "segment": "Transport Vendor", "hq_country": "US", "hq_city": "Huntsville",
     "founded_year": 1985, "employee_count": 3200, "revenue_usd_bn": 0.8, "revenue_year": 2023,
     "ticker": "ADTN", "public": True, "website": "https://www.adtran.com",
     "description": "Provider of networking and communications equipment for fiber broadband infrastructure."},

    # US Mobile Operators
    {"name": "Verizon", "segment": "Mobile Operator", "hq_country": "US", "hq_city": "New York",
     "founded_year": 2000, "employee_count": 105000, "revenue_usd_bn": 134.0, "revenue_year": 2023,
     "ticker": "VZ", "public": True, "website": "https://www.verizon.com",
     "description": "Largest US wireless carrier providing mobile, broadband, and enterprise communications services."},
    {"name": "AT&T", "segment": "Mobile Operator", "hq_country": "US", "hq_city": "Dallas",
     "founded_year": 1983, "employee_count": 152000, "revenue_usd_bn": 122.4, "revenue_year": 2023,
     "ticker": "T", "public": True, "website": "https://www.att.com",
     "description": "American multinational telecommunications conglomerate providing wireless, broadband, and media services."},
    {"name": "T-Mobile", "segment": "Mobile Operator", "hq_country": "US", "hq_city": "Bellevue",
     "founded_year": 1994, "employee_count": 71000, "revenue_usd_bn": 79.5, "revenue_year": 2023,
     "ticker": "TMUS", "public": True, "website": "https://www.t-mobile.com",
     "description": "US wireless carrier known for disrupting the industry and leading in 5G mid-band deployment."},
    {"name": "Sprint", "segment": "Mobile Operator", "hq_country": "US", "hq_city": "Overland Park",
     "founded_year": 1899, "public": False,
     "description": "Former US wireless carrier acquired by T-Mobile in 2020."},

    # EU Mobile Operators
    {"name": "Vodafone", "segment": "Mobile Operator", "hq_country": "GB", "hq_city": "Newbury",
     "founded_year": 1984, "employee_count": 104000, "revenue_usd_bn": 47.0, "revenue_year": 2023,
     "ticker": "VOD", "public": True, "website": "https://www.vodafone.com",
     "description": "British multinational telecom company operating across Europe, Africa, and Asia-Pacific."},
    {"name": "Deutsche Telekom", "segment": "Mobile Operator", "hq_country": "DE", "hq_city": "Bonn",
     "founded_year": 1995, "employee_count": 206000, "revenue_usd_bn": 121.0, "revenue_year": 2023,
     "ticker": "DTE.DE", "public": True, "website": "https://www.telekom.com",
     "description": "German telecommunications company and majority shareholder of T-Mobile US."},
    {"name": "Orange", "segment": "Mobile Operator", "hq_country": "FR", "hq_city": "Paris",
     "founded_year": 1994, "employee_count": 137000, "revenue_usd_bn": 46.1, "revenue_year": 2023,
     "ticker": "ORA.PA", "public": True, "website": "https://www.orange.com",
     "description": "French multinational telecommunications corporation serving Europe, Africa, and the Middle East."},
    {"name": "BT Group", "segment": "Mobile Operator", "hq_country": "GB", "hq_city": "London",
     "founded_year": 1846, "employee_count": 95000, "revenue_usd_bn": 23.0, "revenue_year": 2023,
     "ticker": "BT.A", "public": True, "website": "https://www.bt.com",
     "description": "British multinational telecom company providing fixed, mobile, broadband, and IT services."},

    # Asia Mobile Operators
    {"name": "China Mobile", "segment": "Mobile Operator", "hq_country": "CN", "hq_city": "Beijing",
     "founded_year": 1997, "employee_count": 450000, "revenue_usd_bn": 140.0, "revenue_year": 2023,
     "ticker": "0941.HK", "public": True, "website": "https://www.chinamobileltd.com",
     "description": "World's largest mobile carrier by subscribers with over 1 billion connections."},
    {"name": "China Unicom", "segment": "Mobile Operator", "hq_country": "CN", "hq_city": "Beijing",
     "founded_year": 1994, "employee_count": 260000, "revenue_usd_bn": 49.2, "revenue_year": 2023,
     "ticker": "0762.HK", "public": True, "website": "https://www.chinaunicom.com.hk",
     "description": "Chinese state-owned telecommunications operator providing mobile, broadband and enterprise services."},
    {"name": "China Telecom", "segment": "Mobile Operator", "hq_country": "CN", "hq_city": "Beijing",
     "founded_year": 2002, "employee_count": 375000, "revenue_usd_bn": 62.5, "revenue_year": 2023,
     "ticker": "0728.HK", "public": True, "website": "https://www.chinatelecom-h.com",
     "description": "Chinese state-owned telecommunications company providing fixed, mobile, and broadband services."},
    {"name": "NTT Docomo", "segment": "Mobile Operator", "hq_country": "JP", "hq_city": "Tokyo",
     "founded_year": 1992, "employee_count": 29000, "revenue_usd_bn": 47.3, "revenue_year": 2023,
     "public": False, "website": "https://www.docomo.ne.jp",
     "description": "Japan's largest mobile carrier and subsidiary of NTT Group."},
    {"name": "SoftBank", "segment": "Mobile Operator", "hq_country": "JP", "hq_city": "Tokyo",
     "founded_year": 2006, "employee_count": 52000, "revenue_usd_bn": 59.0, "revenue_year": 2023,
     "ticker": "9984.T", "public": True, "website": "https://www.softbank.jp",
     "description": "Japanese conglomerate with major telecommunications and technology investment businesses."},
    {"name": "Reliance Jio", "segment": "Mobile Operator", "hq_country": "IN", "hq_city": "Mumbai",
     "founded_year": 2016, "employee_count": 23000, "revenue_usd_bn": 13.5, "revenue_year": 2023,
     "public": False, "website": "https://www.jio.com",
     "description": "India's largest mobile carrier, subsidiary of Reliance Industries, pioneering 5G deployment in India."},
    {"name": "Airtel", "segment": "Mobile Operator", "hq_country": "IN", "hq_city": "New Delhi",
     "founded_year": 1995, "employee_count": 19000, "revenue_usd_bn": 17.5, "revenue_year": 2023,
     "ticker": "BHARTIARTL.NS", "public": True, "website": "https://www.airtel.in",
     "description": "Indian multinational telecommunications services company operating in 18 countries across Asia and Africa."},
    {"name": "SK Telecom", "segment": "Mobile Operator", "hq_country": "KR", "hq_city": "Seoul",
     "founded_year": 1984, "employee_count": 22000, "revenue_usd_bn": 18.8, "revenue_year": 2023,
     "ticker": "017670.KS", "public": True, "website": "https://www.sktelecom.com",
     "description": "South Korea's largest wireless carrier and pioneer in 5G commercialization."},
    {"name": "KT Corp", "segment": "Mobile Operator", "hq_country": "KR", "hq_city": "Seoul",
     "founded_year": 1981, "employee_count": 20000, "revenue_usd_bn": 15.2, "revenue_year": 2023,
     "ticker": "030200.KS", "public": True, "website": "https://corp.kt.com",
     "description": "South Korean telecommunications company providing mobile, broadband, and enterprise services."},
    {"name": "Dish Network", "segment": "Mobile Operator", "hq_country": "US", "hq_city": "Englewood",
     "founded_year": 1980, "employee_count": 16000, "public": True, "ticker": "DISH",
     "website": "https://www.dish.com",
     "description": "US satellite TV and wireless carrier building a cloud-native Open RAN 5G network from scratch."},

    # Hyperscalers
    {"name": "AWS", "segment": "Hyperscaler", "hq_country": "US", "hq_city": "Seattle",
     "founded_year": 2006, "public": False, "website": "https://aws.amazon.com",
     "description": "Amazon's cloud computing division offering telecom-focused services including Wavelength and Private 5G."},
    {"name": "Microsoft", "segment": "Hyperscaler", "hq_country": "US", "hq_city": "Redmond",
     "founded_year": 1975, "employee_count": 221000, "revenue_usd_bn": 211.9, "revenue_year": 2023,
     "ticker": "MSFT", "public": True, "website": "https://www.microsoft.com",
     "description": "Global technology company offering Azure Operator Nexus and other telecom cloud solutions."},
    {"name": "Google", "segment": "Hyperscaler", "hq_country": "US", "hq_city": "Mountain View",
     "founded_year": 1998, "employee_count": 182000, "revenue_usd_bn": 307.4, "revenue_year": 2023,
     "ticker": "GOOGL", "public": True, "website": "https://cloud.google.com",
     "description": "Technology giant providing Google Cloud telecom solutions including CCAI and Distributed Cloud Edge."},
    {"name": "IBM", "segment": "Hyperscaler", "hq_country": "US", "hq_city": "Armonk",
     "founded_year": 1911, "employee_count": 288000, "revenue_usd_bn": 61.9, "revenue_year": 2023,
     "ticker": "IBM", "public": True, "website": "https://www.ibm.com",
     "description": "Global technology company with major telecom consulting, automation, and hybrid cloud offerings."},
    {"name": "Oracle", "segment": "Hyperscaler", "hq_country": "US", "hq_city": "Austin",
     "founded_year": 1977, "employee_count": 164000, "revenue_usd_bn": 50.0, "revenue_year": 2023,
     "ticker": "ORCL", "public": True, "website": "https://www.oracle.com",
     "description": "Enterprise software and cloud company with Oracle Communications suite for telecom operators."},

    # Media
    {"name": "Comcast", "segment": "Media", "hq_country": "US", "hq_city": "Philadelphia",
     "founded_year": 1963, "employee_count": 186000, "revenue_usd_bn": 121.6, "revenue_year": 2023,
     "ticker": "CMCSA", "public": True, "website": "https://corporate.comcast.com",
     "description": "American cable, broadband, and media conglomerate owning NBCUniversal and Xfinity services."},
    {"name": "Disney", "segment": "Media", "hq_country": "US", "hq_city": "Burbank",
     "founded_year": 1923, "employee_count": 220000, "revenue_usd_bn": 88.9, "revenue_year": 2023,
     "ticker": "DIS", "public": True, "website": "https://thewaltdisneycompany.com",
     "description": "Global entertainment conglomerate operating Disney+, Hulu, ESPN+, and traditional media properties."},
    {"name": "Netflix", "segment": "Media", "hq_country": "US", "hq_city": "Los Gatos",
     "founded_year": 1997, "employee_count": 13000, "revenue_usd_bn": 33.7, "revenue_year": 2023,
     "ticker": "NFLX", "public": True, "website": "https://www.netflix.com",
     "description": "World's leading subscription video-on-demand streaming service with 270+ million subscribers."},
    {"name": "Warner Bros Discovery", "segment": "Media", "hq_country": "US", "hq_city": "New York",
     "founded_year": 2022, "employee_count": 35000, "revenue_usd_bn": 41.3, "revenue_year": 2023,
     "ticker": "WBD", "public": True, "website": "https://wbd.com",
     "description": "Media and entertainment company operating Max streaming, CNN, HBO, and Warner Bros film studio."},
    {"name": "Paramount Global", "segment": "Media", "hq_country": "US", "hq_city": "New York",
     "founded_year": 2006, "employee_count": 23000, "revenue_usd_bn": 28.6, "revenue_year": 2023,
     "ticker": "PARA", "public": True, "website": "https://www.paramount.com",
     "description": "Global media and entertainment company operating Paramount+, CBS, MTV, and Nickelodeon."},
    {"name": "Apple", "segment": "Media", "hq_country": "US", "hq_city": "Cupertino",
     "founded_year": 1976, "employee_count": 164000, "revenue_usd_bn": 383.3, "revenue_year": 2023,
     "ticker": "AAPL", "public": True, "website": "https://www.apple.com",
     "description": "Technology company with Apple TV+ streaming service and dominant iPhone 5G device ecosystem."},
    {"name": "Amazon", "segment": "Media", "hq_country": "US", "hq_city": "Seattle",
     "founded_year": 1994, "employee_count": 1541000, "revenue_usd_bn": 554.0, "revenue_year": 2023,
     "ticker": "AMZN", "public": True, "website": "https://www.amazon.com",
     "description": "E-commerce and cloud giant operating Amazon Prime Video and AWS cloud infrastructure."},
    {"name": "Activision Blizzard", "segment": "Media", "hq_country": "US", "hq_city": "Santa Monica",
     "founded_year": 1979, "public": False,
     "description": "Video game company acquired by Microsoft in 2023, maker of Call of Duty and World of Warcraft."},

    # Chipmakers
    {"name": "Qualcomm", "segment": "Chipmaker", "hq_country": "US", "hq_city": "San Diego",
     "founded_year": 1985, "employee_count": 51000, "revenue_usd_bn": 35.8, "revenue_year": 2023,
     "ticker": "QCOM", "public": True, "website": "https://www.qualcomm.com",
     "description": "Semiconductor and telecom equipment company dominating 5G modem and RAN silicon markets."},
    {"name": "MediaTek", "segment": "Chipmaker", "hq_country": "TW", "hq_city": "Hsinchu",
     "founded_year": 1997, "employee_count": 20000, "revenue_usd_bn": 13.5, "revenue_year": 2023,
     "ticker": "2454.TW", "public": True, "website": "https://www.mediatek.com",
     "description": "Taiwanese fabless semiconductor company providing 5G chipsets primarily for mid-range devices."},
    {"name": "Intel", "segment": "Chipmaker", "hq_country": "US", "hq_city": "Santa Clara",
     "founded_year": 1968, "employee_count": 124800, "revenue_usd_bn": 54.2, "revenue_year": 2023,
     "ticker": "INTC", "public": True, "website": "https://www.intel.com",
     "description": "Semiconductor company providing vRAN acceleration hardware and server silicon for telecom infrastructure."},
    {"name": "Marvell Technology", "segment": "Chipmaker", "hq_country": "US", "hq_city": "Santa Clara",
     "founded_year": 1997, "employee_count": 6300, "revenue_usd_bn": 5.5, "revenue_year": 2023,
     "ticker": "MRVL", "public": True, "website": "https://www.marvell.com",
     "description": "Data infrastructure semiconductor company providing silicon for Open RAN and 5G infrastructure."},
    {"name": "Nvidia", "segment": "Chipmaker", "hq_country": "US", "hq_city": "Santa Clara",
     "founded_year": 1993, "employee_count": 29600, "revenue_usd_bn": 60.9, "revenue_year": 2023,
     "ticker": "NVDA", "public": True, "website": "https://www.nvidia.com",
     "description": "GPU and AI accelerator company with growing presence in AI-driven telecom and vRAN acceleration."},
    {"name": "Arm Holdings", "segment": "Chipmaker", "hq_country": "GB", "hq_city": "Cambridge",
     "founded_year": 1990, "employee_count": 6000, "revenue_usd_bn": 2.7, "revenue_year": 2023,
     "ticker": "ARM", "public": True, "website": "https://www.arm.com",
     "description": "British semiconductor IP company providing processor architecture used in most 5G chips."},
    {"name": "Broadcom", "segment": "Chipmaker", "hq_country": "US", "hq_city": "San Jose",
     "founded_year": 1991, "employee_count": 20000, "revenue_usd_bn": 35.8, "revenue_year": 2023,
     "ticker": "AVGO", "public": True, "website": "https://www.broadcom.com",
     "description": "Semiconductor and infrastructure software company with networking ASICs and Wi-Fi chip products."},

    # Satellite
    {"name": "SpaceX", "segment": "Satellite", "hq_country": "US", "hq_city": "Hawthorne",
     "founded_year": 2002, "employee_count": 13000, "public": False,
     "website": "https://www.spacex.com",
     "description": "Aerospace company operating Starlink, the world's largest LEO broadband satellite constellation."},
    {"name": "OneWeb", "segment": "Satellite", "hq_country": "GB", "hq_city": "London",
     "founded_year": 2012, "employee_count": 800, "public": False,
     "website": "https://oneweb.net",
     "description": "Satellite internet company operating a LEO constellation, now part of Eutelsat."},
    {"name": "Intelsat", "segment": "Satellite", "hq_country": "LU", "hq_city": "Luxembourg",
     "founded_year": 1964, "employee_count": 1900, "public": False,
     "website": "https://www.intelsat.com",
     "description": "GEO satellite operator providing broadband, media distribution, and government connectivity."},
    {"name": "Viasat", "segment": "Satellite", "hq_country": "US", "hq_city": "Carlsbad",
     "founded_year": 1986, "employee_count": 7200, "revenue_usd_bn": 4.2, "revenue_year": 2023,
     "ticker": "VSAT", "public": True, "website": "https://www.viasat.com",
     "description": "Satellite and digital networking company providing broadband internet via GEO and LEO satellites."},
    {"name": "SES", "segment": "Satellite", "hq_country": "LU", "hq_city": "Betzdorf",
     "founded_year": 1985, "employee_count": 2100, "revenue_usd_bn": 2.0, "revenue_year": 2023,
     "ticker": "SESG.PA", "public": True, "website": "https://www.ses.com",
     "description": "Luxembourg-based satellite operator with GEO and MEO fleets serving media and broadband markets."},

    # CDN / Edge
    {"name": "Akamai", "segment": "CDN", "hq_country": "US", "hq_city": "Cambridge",
     "founded_year": 1998, "employee_count": 10500, "revenue_usd_bn": 3.8, "revenue_year": 2023,
     "ticker": "AKAM", "public": True, "website": "https://www.akamai.com",
     "description": "World's largest CDN and edge cloud platform, delivering 15-30% of global web traffic."},
    {"name": "Cloudflare", "segment": "CDN", "hq_country": "US", "hq_city": "San Francisco",
     "founded_year": 2009, "employee_count": 3700, "revenue_usd_bn": 1.3, "revenue_year": 2023,
     "ticker": "NET", "public": True, "website": "https://www.cloudflare.com",
     "description": "Global network company providing CDN, DDoS protection, Zero Trust security, and edge computing."},
    {"name": "Fastly", "segment": "CDN", "hq_country": "US", "hq_city": "San Francisco",
     "founded_year": 2011, "employee_count": 1100, "revenue_usd_bn": 0.5, "revenue_year": 2023,
     "ticker": "FSLY", "public": True, "website": "https://www.fastly.com",
     "description": "Edge cloud platform providing CDN, edge compute, and security services for digital businesses."},
]
