RELATIONSHIPS = [
    # === COMPETES_WITH ===
    {"source": "Ericsson", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Nokia", "target_label": "Company", "props": {"segment": "RAN", "intensity": "High"}},
    {"source": "Ericsson", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Huawei", "target_label": "Company", "props": {"segment": "RAN", "intensity": "High"}},
    {"source": "Ericsson", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Samsung Networks", "target_label": "Company", "props": {"segment": "RAN", "intensity": "Medium"}},
    {"source": "Ericsson", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "ZTE", "target_label": "Company", "props": {"segment": "RAN", "intensity": "Medium"}},
    {"source": "Nokia", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Huawei", "target_label": "Company", "props": {"segment": "RAN", "intensity": "High"}},
    {"source": "Nokia", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Samsung Networks", "target_label": "Company", "props": {"segment": "RAN", "intensity": "Medium"}},
    {"source": "Nokia", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "ZTE", "target_label": "Company", "props": {"segment": "RAN", "intensity": "Medium"}},
    {"source": "Qualcomm", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "MediaTek", "target_label": "Company", "props": {"segment": "5G Modems", "intensity": "High"}},
    {"source": "Qualcomm", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Intel", "target_label": "Company", "props": {"segment": "RAN Silicon", "intensity": "Medium"}},
    {"source": "Akamai", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Cloudflare", "target_label": "Company", "props": {"segment": "CDN", "intensity": "High"}},
    {"source": "Akamai", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Fastly", "target_label": "Company", "props": {"segment": "CDN", "intensity": "Medium"}},
    {"source": "Netflix", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Disney", "target_label": "Company", "props": {"segment": "Video Streaming", "intensity": "High"}},
    {"source": "Netflix", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Amazon", "target_label": "Company", "props": {"segment": "Video Streaming", "intensity": "High"}},
    {"source": "Netflix", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Warner Bros Discovery", "target_label": "Company", "props": {"segment": "Video Streaming", "intensity": "High"}},
    {"source": "Netflix", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Apple", "target_label": "Company", "props": {"segment": "Video Streaming", "intensity": "Medium"}},
    {"source": "Netflix", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Paramount Global", "target_label": "Company", "props": {"segment": "Video Streaming", "intensity": "Medium"}},
    {"source": "Verizon", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "AT&T", "target_label": "Company", "props": {"segment": "US Mobile", "intensity": "High"}},
    {"source": "T-Mobile", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Verizon", "target_label": "Company", "props": {"segment": "US Mobile", "intensity": "High"}},
    {"source": "T-Mobile", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "AT&T", "target_label": "Company", "props": {"segment": "US Mobile", "intensity": "High"}},
    {"source": "Vodafone", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Deutsche Telekom", "target_label": "Company", "props": {"segment": "EU Mobile", "intensity": "High"}},
    {"source": "SpaceX", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "OneWeb", "target_label": "Company", "props": {"segment": "LEO Satellite", "intensity": "High"}},
    {"source": "SpaceX", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Viasat", "target_label": "Company", "props": {"segment": "Satellite Broadband", "intensity": "Medium"}},
    {"source": "AWS", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Microsoft", "target_label": "Company", "props": {"segment": "Telecom Cloud", "intensity": "High"}},
    {"source": "AWS", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Google", "target_label": "Company", "props": {"segment": "Telecom Cloud", "intensity": "High"}},
    {"source": "Reliance Jio", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Airtel", "target_label": "Company", "props": {"segment": "India Mobile", "intensity": "High"}},
    {"source": "SK Telecom", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "KT Corp", "target_label": "Company", "props": {"segment": "Korea Mobile", "intensity": "High"}},
    {"source": "Mavenir", "source_label": "Company", "type": "COMPETES_WITH",
     "target": "Parallel Wireless", "target_label": "Company", "props": {"segment": "Open RAN Software", "intensity": "High"}},

    # === MEMBER_OF ===
    {"source": "Ericsson", "source_label": "Company", "type": "MEMBER_OF",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "Nokia", "source_label": "Company", "type": "MEMBER_OF",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "Huawei", "source_label": "Company", "type": "MEMBER_OF",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "ZTE", "source_label": "Company", "type": "MEMBER_OF",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "Samsung Networks", "source_label": "Company", "type": "MEMBER_OF",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "Qualcomm", "source_label": "Company", "type": "MEMBER_OF",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "Intel", "source_label": "Company", "type": "MEMBER_OF",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "Verizon", "source_label": "Company", "type": "MEMBER_OF",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "AT&T", "source_label": "Company", "type": "MEMBER_OF",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "T-Mobile", "source_label": "Company", "type": "MEMBER_OF",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "Vodafone", "source_label": "Company", "type": "MEMBER_OF",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "Deutsche Telekom", "source_label": "Company", "type": "MEMBER_OF",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "Ericsson", "source_label": "Company", "type": "MEMBER_OF",
     "target": "GSMA", "target_label": "RegBody", "props": {}},
    {"source": "Nokia", "source_label": "Company", "type": "MEMBER_OF",
     "target": "GSMA", "target_label": "RegBody", "props": {}},
    {"source": "Huawei", "source_label": "Company", "type": "MEMBER_OF",
     "target": "GSMA", "target_label": "RegBody", "props": {}},
    {"source": "Verizon", "source_label": "Company", "type": "MEMBER_OF",
     "target": "GSMA", "target_label": "RegBody", "props": {}},
    {"source": "Ericsson", "source_label": "Company", "type": "MEMBER_OF",
     "target": "O-RAN Alliance", "target_label": "RegBody", "props": {}},
    {"source": "Nokia", "source_label": "Company", "type": "MEMBER_OF",
     "target": "O-RAN Alliance", "target_label": "RegBody", "props": {}},
    {"source": "AT&T", "source_label": "Company", "type": "MEMBER_OF",
     "target": "O-RAN Alliance", "target_label": "RegBody", "props": {}},
    {"source": "Mavenir", "source_label": "Company", "type": "MEMBER_OF",
     "target": "O-RAN Alliance", "target_label": "RegBody", "props": {}},
    {"source": "Parallel Wireless", "source_label": "Company", "type": "MEMBER_OF",
     "target": "O-RAN Alliance", "target_label": "RegBody", "props": {}},
    {"source": "Ericsson", "source_label": "Company", "type": "MEMBER_OF",
     "target": "ETSI", "target_label": "RegBody", "props": {}},
    {"source": "Nokia", "source_label": "Company", "type": "MEMBER_OF",
     "target": "ETSI", "target_label": "RegBody", "props": {}},
    {"source": "Ericsson", "source_label": "Company", "type": "MEMBER_OF",
     "target": "TM Forum", "target_label": "RegBody", "props": {}},
    {"source": "Netflix", "source_label": "Company", "type": "MEMBER_OF",
     "target": "Alliance for Open Media", "target_label": "RegBody", "props": {}},
    {"source": "Google", "source_label": "Company", "type": "MEMBER_OF",
     "target": "Alliance for Open Media", "target_label": "RegBody", "props": {}},
    {"source": "Amazon", "source_label": "Company", "type": "MEMBER_OF",
     "target": "Alliance for Open Media", "target_label": "RegBody", "props": {}},
    {"source": "Microsoft", "source_label": "Company", "type": "MEMBER_OF",
     "target": "Alliance for Open Media", "target_label": "RegBody", "props": {}},
    {"source": "Apple", "source_label": "Company", "type": "MEMBER_OF",
     "target": "Alliance for Open Media", "target_label": "RegBody", "props": {}},

    # === ISSUED_BY ===
    {"source": "3GPP Release 15", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "3GPP Release 16", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "3GPP Release 17", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "3GPP Release 18", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "3GPP Release 19", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "TS 38.101", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "TS 38.300", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "TS 23.501", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "TS 23.502", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "TS 33.501", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "3GPP", "target_label": "RegBody", "props": {}},
    {"source": "IMT-2020", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "ITU-R", "target_label": "RegBody", "props": {}},
    {"source": "IMT-2030", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "ITU-R", "target_label": "RegBody", "props": {}},
    {"source": "G.709", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "ITU-T", "target_label": "RegBody", "props": {}},
    {"source": "H.265/HEVC", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "ITU-T", "target_label": "RegBody", "props": {}},
    {"source": "H.266/VVC", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "ITU-T", "target_label": "RegBody", "props": {}},
    {"source": "ETSI NFV", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "ETSI", "target_label": "RegBody", "props": {}},
    {"source": "ETSI MEC", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "ETSI", "target_label": "RegBody", "props": {}},
    {"source": "O-RAN WG1", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "O-RAN Alliance", "target_label": "RegBody", "props": {}},
    {"source": "O-RAN WG4", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "O-RAN Alliance", "target_label": "RegBody", "props": {}},
    {"source": "O-RAN WG6", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "O-RAN Alliance", "target_label": "RegBody", "props": {}},
    {"source": "IEEE 802.11ax", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "IEEE", "target_label": "RegBody", "props": {}},
    {"source": "IEEE 802.3", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "IEEE", "target_label": "RegBody", "props": {}},
    {"source": "MPEG-DASH", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "IETF", "target_label": "RegBody", "props": {}},
    {"source": "HLS", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "IETF", "target_label": "RegBody", "props": {}},
    {"source": "AV1", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "Alliance for Open Media", "target_label": "RegBody", "props": {}},
    {"source": "ATSC 3.0", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "ATSC", "target_label": "RegBody", "props": {}},
    {"source": "SMPTE ST 2110", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "SMPTE", "target_label": "RegBody", "props": {}},
    {"source": "DOCSIS 3.1", "source_label": "Standard", "type": "ISSUED_BY",
     "target": "Broadband Forum", "target_label": "RegBody", "props": {}},

    # === SUPERSEDES ===
    {"source": "3GPP Release 16", "source_label": "Standard", "type": "SUPERSEDES",
     "target": "3GPP Release 15", "target_label": "Standard", "props": {}},
    {"source": "3GPP Release 17", "source_label": "Standard", "type": "SUPERSEDES",
     "target": "3GPP Release 16", "target_label": "Standard", "props": {}},
    {"source": "3GPP Release 18", "source_label": "Standard", "type": "SUPERSEDES",
     "target": "3GPP Release 17", "target_label": "Standard", "props": {}},
    {"source": "3GPP Release 19", "source_label": "Standard", "type": "SUPERSEDES",
     "target": "3GPP Release 18", "target_label": "Standard", "props": {}},
    {"source": "H.266/VVC", "source_label": "Standard", "type": "SUPERSEDES",
     "target": "H.265/HEVC", "target_label": "Standard", "props": {}},
    {"source": "IMT-2030", "source_label": "Standard", "type": "SUPERSEDES",
     "target": "IMT-2020", "target_label": "Standard", "props": {}},

    # === DEFINES (Standard → Technology) ===
    {"source": "3GPP Release 15", "source_label": "Standard", "type": "DEFINES",
     "target": "5G NR", "target_label": "Technology", "props": {}},
    {"source": "3GPP Release 15", "source_label": "Standard", "type": "DEFINES",
     "target": "5G Core", "target_label": "Technology", "props": {}},
    {"source": "3GPP Release 15", "source_label": "Standard", "type": "DEFINES",
     "target": "Service Based Architecture", "target_label": "Technology", "props": {}},
    {"source": "3GPP Release 16", "source_label": "Standard", "type": "DEFINES",
     "target": "URLLC", "target_label": "Technology", "props": {}},
    {"source": "3GPP Release 16", "source_label": "Standard", "type": "DEFINES",
     "target": "Network Slicing", "target_label": "Technology", "props": {}},
    {"source": "3GPP Release 17", "source_label": "Standard", "type": "DEFINES",
     "target": "Massive MIMO", "target_label": "Technology", "props": {}},
    {"source": "3GPP Release 17", "source_label": "Standard", "type": "DEFINES",
     "target": "Private 5G", "target_label": "Technology", "props": {}},
    {"source": "3GPP Release 18", "source_label": "Standard", "type": "DEFINES",
     "target": "RAN Intelligent Controller", "target_label": "Technology", "props": {}},
    {"source": "3GPP Release 18", "source_label": "Standard", "type": "DEFINES",
     "target": "AIOps for Networks", "target_label": "Technology", "props": {}},
    {"source": "IMT-2020", "source_label": "Standard", "type": "DEFINES",
     "target": "5G NR", "target_label": "Technology", "props": {}},
    {"source": "O-RAN WG1", "source_label": "Standard", "type": "DEFINES",
     "target": "O-RAN", "target_label": "Technology", "props": {}},
    {"source": "O-RAN WG4", "source_label": "Standard", "type": "DEFINES",
     "target": "O-RAN", "target_label": "Technology", "props": {}},
    {"source": "ETSI NFV", "source_label": "Standard", "type": "DEFINES",
     "target": "Network Function Virtualization", "target_label": "Technology", "props": {}},
    {"source": "ETSI MEC", "source_label": "Standard", "type": "DEFINES",
     "target": "Multi-access Edge Computing", "target_label": "Technology", "props": {}},

    # === ENABLES (Technology → Technology) ===
    {"source": "Massive MIMO", "source_label": "Technology", "type": "ENABLES",
     "target": "5G NR", "target_label": "Technology", "props": {}},
    {"source": "Beamforming", "source_label": "Technology", "type": "ENABLES",
     "target": "Massive MIMO", "target_label": "Technology", "props": {}},
    {"source": "mmWave", "source_label": "Technology", "type": "ENABLES",
     "target": "5G NR", "target_label": "Technology", "props": {}},
    {"source": "5G NR", "source_label": "Technology", "type": "ENABLES",
     "target": "Network Slicing", "target_label": "Technology", "props": {}},
    {"source": "5G NR", "source_label": "Technology", "type": "ENABLES",
     "target": "URLLC", "target_label": "Technology", "props": {}},
    {"source": "5G NR", "source_label": "Technology", "type": "ENABLES",
     "target": "eMBB", "target_label": "Technology", "props": {}},
    {"source": "5G NR", "source_label": "Technology", "type": "ENABLES",
     "target": "Private 5G", "target_label": "Technology", "props": {}},
    {"source": "Network Slicing", "source_label": "Technology", "type": "ENABLES",
     "target": "Private 5G", "target_label": "Technology", "props": {}},
    {"source": "Network Function Virtualization", "source_label": "Technology", "type": "ENABLES",
     "target": "Network Slicing", "target_label": "Technology", "props": {}},
    {"source": "Network Function Virtualization", "source_label": "Technology", "type": "ENABLES",
     "target": "Telco Cloud", "target_label": "Technology", "props": {}},
    {"source": "Telco Cloud", "source_label": "Technology", "type": "ENABLES",
     "target": "Multi-access Edge Computing", "target_label": "Technology", "props": {}},
    {"source": "Multi-access Edge Computing", "source_label": "Technology", "type": "ENABLES",
     "target": "Private 5G", "target_label": "Technology", "props": {}},
    {"source": "O-RAN", "source_label": "Technology", "type": "ENABLES",
     "target": "vRAN", "target_label": "Technology", "props": {}},
    {"source": "vRAN", "source_label": "Technology", "type": "ENABLES",
     "target": "Cloud RAN", "target_label": "Technology", "props": {}},
    {"source": "RAN Intelligent Controller", "source_label": "Technology", "type": "ENABLES",
     "target": "AIOps for Networks", "target_label": "Technology", "props": {}},
    {"source": "Optical Transport Network", "source_label": "Technology", "type": "ENABLES",
     "target": "DWDM", "target_label": "Technology", "props": {}},
    {"source": "Coherent Optics", "source_label": "Technology", "type": "ENABLES",
     "target": "DWDM", "target_label": "Technology", "props": {}},
    {"source": "Content Delivery Network", "source_label": "Technology", "type": "ENABLES",
     "target": "OTT Streaming", "target_label": "Technology", "props": {}},
    {"source": "OTT Streaming", "source_label": "Technology", "type": "ENABLES",
     "target": "FAST Channels", "target_label": "Technology", "props": {}},
    {"source": "Adaptive Bitrate Streaming", "source_label": "Technology", "type": "ENABLES",
     "target": "OTT Streaming", "target_label": "Technology", "props": {}},

    # === REQUIRES (Technology → Technology) ===
    {"source": "5G NR", "source_label": "Technology", "type": "REQUIRES",
     "target": "Beamforming", "target_label": "Technology", "props": {}},
    {"source": "Massive MIMO", "source_label": "Technology", "type": "REQUIRES",
     "target": "Beamforming", "target_label": "Technology", "props": {}},
    {"source": "Network Slicing", "source_label": "Technology", "type": "REQUIRES",
     "target": "Network Function Virtualization", "target_label": "Technology", "props": {}},
    {"source": "vRAN", "source_label": "Technology", "type": "REQUIRES",
     "target": "Kubernetes for CNFs", "target_label": "Technology", "props": {}},
    {"source": "Cloud RAN", "source_label": "Technology", "type": "REQUIRES",
     "target": "Kubernetes for CNFs", "target_label": "Technology", "props": {}},
    {"source": "xApps and rApps", "source_label": "Technology", "type": "REQUIRES",
     "target": "RAN Intelligent Controller", "target_label": "Technology", "props": {}},
    {"source": "SRv6", "source_label": "Technology", "type": "REQUIRES",
     "target": "Segment Routing", "target_label": "Technology", "props": {}},
    {"source": "Multi-access Edge Computing", "source_label": "Technology", "type": "REQUIRES",
     "target": "5G Core", "target_label": "Technology", "props": {}},

    # === TECHNOLOGY USED_IN MARKET ===
    {"source": "5G NR", "source_label": "Technology", "type": "USED_IN",
     "target": "Enterprise 5G", "target_label": "Market", "props": {}},
    {"source": "Private 5G", "source_label": "Technology", "type": "USED_IN",
     "target": "Private 5G Networks", "target_label": "Market", "props": {}},
    {"source": "Network Slicing", "source_label": "Technology", "type": "USED_IN",
     "target": "Network Slicing Market", "target_label": "Market", "props": {}},
    {"source": "O-RAN", "source_label": "Technology", "type": "USED_IN",
     "target": "Open RAN Market", "target_label": "Market", "props": {}},
    {"source": "Multi-access Edge Computing", "source_label": "Technology", "type": "USED_IN",
     "target": "Telecom Edge Computing", "target_label": "Market", "props": {}},
    {"source": "OTT Streaming", "source_label": "Technology", "type": "USED_IN",
     "target": "Video Streaming", "target_label": "Market", "props": {}},
    {"source": "FAST Channels", "source_label": "Technology", "type": "USED_IN",
     "target": "Video Streaming", "target_label": "Market", "props": {}},

    # === PARTNERED_WITH ===
    {"source": "AWS", "source_label": "Company", "type": "PARTNERED_WITH",
     "target": "Verizon", "target_label": "Company",
     "props": {"partnership_type": "Technology", "description": "Private 5G edge computing partnership", "active": True}},
    {"source": "Nokia", "source_label": "Company", "type": "PARTNERED_WITH",
     "target": "AWS", "target_label": "Company",
     "props": {"partnership_type": "Technology", "description": "5G Cloud RAN on AWS cloud infrastructure", "active": True}},
    {"source": "Ericsson", "source_label": "Company", "type": "PARTNERED_WITH",
     "target": "Microsoft", "target_label": "Company",
     "props": {"partnership_type": "Technology", "description": "5G Azure Private MEC and cloud RAN integration", "active": True}},
    {"source": "Qualcomm", "source_label": "Company", "type": "PARTNERED_WITH",
     "target": "Ericsson", "target_label": "Company",
     "props": {"partnership_type": "Technology", "description": "5G RAN silicon development partnership", "active": True}},
    {"source": "Google", "source_label": "Company", "type": "PARTNERED_WITH",
     "target": "Dish Network", "target_label": "Company",
     "props": {"partnership_type": "Technology", "description": "Open RAN 5G network build on Google Cloud", "active": True}},
    {"source": "Samsung Networks", "source_label": "Company", "type": "PARTNERED_WITH",
     "target": "Verizon", "target_label": "Company",
     "props": {"partnership_type": "Commercial", "description": "Major 5G RAN supply contract for US nationwide network", "active": True}},

    # === SUPPLIES_TO ===
    {"source": "Ericsson", "source_label": "Company", "type": "SUPPLIES_TO",
     "target": "Verizon", "target_label": "Company", "props": {"product_category": "RAN"}},
    {"source": "Ericsson", "source_label": "Company", "type": "SUPPLIES_TO",
     "target": "AT&T", "target_label": "Company", "props": {"product_category": "RAN"}},
    {"source": "Ericsson", "source_label": "Company", "type": "SUPPLIES_TO",
     "target": "Vodafone", "target_label": "Company", "props": {"product_category": "RAN"}},
    {"source": "Nokia", "source_label": "Company", "type": "SUPPLIES_TO",
     "target": "T-Mobile", "target_label": "Company", "props": {"product_category": "RAN"}},
    {"source": "Nokia", "source_label": "Company", "type": "SUPPLIES_TO",
     "target": "BT Group", "target_label": "Company", "props": {"product_category": "RAN"}},
    {"source": "Nokia", "source_label": "Company", "type": "SUPPLIES_TO",
     "target": "Deutsche Telekom", "target_label": "Company", "props": {"product_category": "RAN"}},
    {"source": "Huawei", "source_label": "Company", "type": "SUPPLIES_TO",
     "target": "China Mobile", "target_label": "Company", "props": {"product_category": "RAN"}},
    {"source": "Huawei", "source_label": "Company", "type": "SUPPLIES_TO",
     "target": "China Unicom", "target_label": "Company", "props": {"product_category": "RAN"}},
    {"source": "Samsung Networks", "source_label": "Company", "type": "SUPPLIES_TO",
     "target": "T-Mobile", "target_label": "Company", "props": {"product_category": "RAN"}},
    {"source": "Qualcomm", "source_label": "Company", "type": "SUPPLIES_TO",
     "target": "Apple", "target_label": "Company", "props": {"product_category": "5G Chipset"}},
    {"source": "Ciena", "source_label": "Company", "type": "SUPPLIES_TO",
     "target": "AT&T", "target_label": "Company", "props": {"product_category": "Transport"}},
    {"source": "Ciena", "source_label": "Company", "type": "SUPPLIES_TO",
     "target": "Verizon", "target_label": "Company", "props": {"product_category": "Transport"}},

    # === CONTRIBUTED_TO ===
    {"source": "Ericsson", "source_label": "Company", "type": "CONTRIBUTED_TO",
     "target": "3GPP Release 18", "target_label": "Standard",
     "props": {"contribution_type": "Editor", "num_contributions": 450}},
    {"source": "Nokia", "source_label": "Company", "type": "CONTRIBUTED_TO",
     "target": "3GPP Release 18", "target_label": "Standard",
     "props": {"contribution_type": "Contributor", "num_contributions": 380}},
    {"source": "Huawei", "source_label": "Company", "type": "CONTRIBUTED_TO",
     "target": "3GPP Release 18", "target_label": "Standard",
     "props": {"contribution_type": "Contributor", "num_contributions": 520}},
    {"source": "Qualcomm", "source_label": "Company", "type": "CONTRIBUTED_TO",
     "target": "3GPP Release 18", "target_label": "Standard",
     "props": {"contribution_type": "Contributor", "num_contributions": 290}},
    {"source": "Samsung Networks", "source_label": "Company", "type": "CONTRIBUTED_TO",
     "target": "3GPP Release 18", "target_label": "Standard",
     "props": {"contribution_type": "Contributor", "num_contributions": 180}},
    {"source": "Ericsson", "source_label": "Company", "type": "CONTRIBUTED_TO",
     "target": "3GPP Release 17", "target_label": "Standard",
     "props": {"contribution_type": "Editor", "num_contributions": 410}},
    {"source": "Nokia", "source_label": "Company", "type": "CONTRIBUTED_TO",
     "target": "3GPP Release 17", "target_label": "Standard",
     "props": {"contribution_type": "Contributor", "num_contributions": 350}},
    {"source": "Huawei", "source_label": "Company", "type": "CONTRIBUTED_TO",
     "target": "3GPP Release 17", "target_label": "Standard",
     "props": {"contribution_type": "Contributor", "num_contributions": 480}},

    # === ACQUIRED (direct relationship) ===
    {"source": "T-Mobile", "source_label": "Company", "type": "ACQUIRED",
     "target": "Sprint", "target_label": "Company",
     "props": {"completed_date": "2020-04-01", "value_usd_bn": 26.5, "status": "Completed"}},
    {"source": "Microsoft", "source_label": "Company", "type": "ACQUIRED",
     "target": "Activision Blizzard", "target_label": "Company",
     "props": {"completed_date": "2023-10-13", "value_usd_bn": 68.7, "status": "Completed"}},
]

EVENTS = [
    {"name": "T-Mobile Acquires Sprint", "event_type": "M&A",
     "date": "2020-04-01", "value_usd_bn": 26.5, "status": "Completed",
     "description": "T-Mobile completed its $26.5B acquisition of Sprint, combining the third and fourth largest US carriers to challenge Verizon and AT&T.",
     "involves": ["T-Mobile", "Sprint"]},
    {"name": "Microsoft Acquires Activision Blizzard", "event_type": "M&A",
     "date": "2023-10-13", "value_usd_bn": 68.7, "status": "Completed",
     "description": "Microsoft completed the largest gaming acquisition in history, gaining Call of Duty, Warcraft, and a massive gaming content library.",
     "involves": ["Microsoft", "Activision Blizzard"]},
    {"name": "Amazon Acquires MGM", "event_type": "M&A",
     "date": "2022-03-17", "value_usd_bn": 8.5, "status": "Completed",
     "description": "Amazon acquired MGM Studios to bolster Prime Video content library with iconic film and TV franchises.",
     "involves": ["Amazon"]},
    {"name": "Broadcom Qualcomm Bid Blocked", "event_type": "M&A",
     "date": "2018-03-12", "value_usd_bn": 117.0, "status": "Cancelled",
     "description": "Broadcom's $117B hostile takeover bid for Qualcomm was blocked by US President Trump on national security grounds.",
     "involves": ["Qualcomm", "Broadcom"]},
    {"name": "Oracle Acquires Cerner", "event_type": "M&A",
     "date": "2022-06-07", "value_usd_bn": 28.3, "status": "Completed",
     "description": "Oracle acquired healthcare IT company Cerner to build a national health records database and expand enterprise cloud.",
     "involves": ["Oracle"]},
    {"name": "Verizon TracFone Acquisition", "event_type": "M&A",
     "date": "2021-11-23", "value_usd_bn": 6.25, "status": "Completed",
     "description": "Verizon acquired prepaid carrier TracFone to expand its prepaid market and add 21 million subscribers.",
     "involves": ["Verizon"]},
    {"name": "AWS Verizon Private 5G Partnership", "event_type": "Partnership",
     "date": "2020-12-01", "status": "Active",
     "description": "AWS and Verizon partner to deliver private 5G edge computing services for enterprises across US.",
     "involves": ["AWS", "Verizon"]},
    {"name": "Nokia AWS 5G Cloud RAN Partnership", "event_type": "Partnership",
     "date": "2022-06-01", "status": "Active",
     "description": "Nokia and AWS partner to offer Cloud RAN running on AWS cloud infrastructure, enabling operators to shift CAPEX to OPEX.",
     "involves": ["Nokia", "AWS"]},
    {"name": "Ericsson Microsoft 5G Azure Private MEC", "event_type": "Partnership",
     "date": "2021-09-22", "status": "Active",
     "description": "Ericsson and Microsoft integrate Ericsson's 5G core with Azure Private MEC for enterprise private network deployments.",
     "involves": ["Ericsson", "Microsoft"]},
    {"name": "Google Dish Network Open RAN Deal", "event_type": "Partnership",
     "date": "2020-08-01", "status": "Active",
     "description": "Google Cloud and Dish Network partner to build Dish's cloud-native Open RAN 5G network on Google Cloud Platform.",
     "involves": ["Google", "Dish Network"]},
    {"name": "3GPP Release 18 Freezing", "event_type": "Standard Release",
     "date": "2024-06-14", "status": "Completed",
     "description": "3GPP froze Release 18 (5G-Advanced), marking the first major evolution of 5G with AI/ML integration and XR optimizations.",
     "involves": ["3GPP"]},
    {"name": "Starlink Direct-to-Cell Launch", "event_type": "Product Launch",
     "date": "2024-01-02", "status": "Active",
     "description": "SpaceX launched Starlink Direct-to-Cell satellites enabling standard smartphones to connect directly to LEO satellites.",
     "involves": ["SpaceX"]},
]

PRODUCTS = [
    {"name": "Ericsson Radio System", "maker": "Ericsson", "product_type": "Hardware",
     "description": "Ericsson's flagship 5G RAN portfolio including massive MIMO radios supporting Sub-6GHz and mmWave.",
     "implements": ["3GPP Release 18"], "uses_tech": ["Massive MIMO", "Beamforming"]},
    {"name": "Ericsson Cloud RAN", "maker": "Ericsson", "product_type": "Software",
     "description": "Ericsson's virtualized baseband software enabling RAN functions on cloud infrastructure.",
     "uses_tech": ["vRAN", "Kubernetes for CNFs"]},
    {"name": "Nokia AirScale", "maker": "Nokia", "product_type": "Hardware",
     "description": "Nokia's end-to-end 5G RAN product line from massive MIMO radios to baseband units.",
     "implements": ["3GPP Release 18"], "uses_tech": ["Massive MIMO", "Beamforming"]},
    {"name": "Nokia ReefShark", "maker": "Nokia", "product_type": "Hardware",
     "description": "Nokia's proprietary chipset for 5G baseband processing with up to 100x efficiency improvement over previous generation.",
     "uses_tech": ["5G NR"]},
    {"name": "Huawei Massive MIMO AAU", "maker": "Huawei", "product_type": "Hardware",
     "description": "Huawei's Active Antenna Unit with integrated massive MIMO for 5G RAN deployments.",
     "implements": ["3GPP Release 17"], "uses_tech": ["Massive MIMO", "Beamforming"]},
    {"name": "ZTE CommonCore", "maker": "ZTE", "product_type": "Software",
     "description": "ZTE's cloud-native 5G core network platform based on microservices architecture.",
     "implements": ["3GPP Release 17"], "uses_tech": ["5G Core", "Service Based Architecture"]},
    {"name": "Snapdragon X75", "maker": "Qualcomm", "product_type": "Hardware",
     "description": "Qualcomm's 5G modem-RF system with AI-enhanced 5G performance for flagship smartphones.",
     "implements": ["3GPP Release 17"], "uses_tech": ["5G NR", "mmWave"]},
    {"name": "Qualcomm X100", "maker": "Qualcomm", "product_type": "Hardware",
     "description": "Qualcomm's RAN acceleration card for Open RAN baseband processing.",
     "uses_tech": ["O-RAN", "vRAN"]},
    {"name": "Intel vRAN Boost", "maker": "Intel", "product_type": "Hardware",
     "description": "Intel's integrated accelerator in 4th Gen Xeon for virtualized RAN baseband processing.",
     "implements": ["O-RAN WG6"], "uses_tech": ["vRAN"]},
    {"name": "Mavenir Open vRAN", "maker": "Mavenir", "product_type": "Software",
     "description": "Mavenir's cloud-native Open RAN software stack supporting O-RAN Alliance interfaces.",
     "implements": ["O-RAN WG4"], "uses_tech": ["O-RAN", "vRAN"]},
    {"name": "Ciena WaveLogic 6", "maker": "Ciena", "product_type": "Hardware",
     "description": "Ciena's coherent optical chipset enabling 800G+ per wavelength for long-haul and metro transport.",
     "uses_tech": ["Coherent Optics", "DWDM"]},
    {"name": "AWS Wavelength", "maker": "AWS", "product_type": "Platform",
     "description": "AWS edge computing zones embedded within telecom operator networks for ultra-low latency applications.",
     "uses_tech": ["Multi-access Edge Computing", "5G Core"]},
    {"name": "Azure Operator Nexus", "maker": "Microsoft", "product_type": "Platform",
     "description": "Microsoft's hybrid cloud platform for telecom operators to run network functions on Azure.",
     "uses_tech": ["Telco Cloud", "Kubernetes for CNFs"]},
    {"name": "Google Distributed Cloud Edge", "maker": "Google", "product_type": "Platform",
     "description": "Google Cloud hardware and software solution for running Google Cloud services at the edge.",
     "uses_tech": ["Multi-access Edge Computing"]},
    {"name": "Akamai Intelligent Edge", "maker": "Akamai", "product_type": "Platform",
     "description": "Akamai's globally distributed edge platform for content delivery, security, and compute.",
     "uses_tech": ["Content Delivery Network", "OTT Streaming"]},
    {"name": "Cloudflare Workers", "maker": "Cloudflare", "product_type": "Platform",
     "description": "Cloudflare's serverless compute platform running code at the network edge in 300+ cities.",
     "uses_tech": ["Content Delivery Network"]},
]
