REG_BODIES = [
    {"name": "3GPP", "full_name": "3rd Generation Partnership Project", "type": "Standards",
     "scope": "Global", "founded_year": 1998, "website": "https://www.3gpp.org", "region": "Global"},
    {"name": "ITU-T", "full_name": "International Telecommunication Union – Telecommunication",
     "type": "Standards", "scope": "Global", "founded_year": 1865, "website": "https://www.itu.int", "region": "Global"},
    {"name": "ITU-R", "full_name": "International Telecommunication Union – Radiocommunication",
     "type": "Regulatory", "scope": "Global", "founded_year": 1865, "website": "https://www.itu.int", "region": "Global"},
    {"name": "ETSI", "full_name": "European Telecommunications Standards Institute",
     "type": "Standards", "scope": "Regional", "founded_year": 1988, "website": "https://www.etsi.org", "region": "Europe"},
    {"name": "GSMA", "full_name": "GSM Association", "type": "Industry Assoc",
     "scope": "Global", "founded_year": 1995, "website": "https://www.gsma.com", "region": "Global"},
    {"name": "IEEE", "full_name": "Institute of Electrical and Electronics Engineers",
     "type": "Standards", "scope": "Global", "founded_year": 1963, "website": "https://www.ieee.org", "region": "Global"},
    {"name": "IETF", "full_name": "Internet Engineering Task Force",
     "type": "Standards", "scope": "Global", "founded_year": 1986, "website": "https://www.ietf.org", "region": "Global"},
    {"name": "O-RAN Alliance", "full_name": "Open Radio Access Network Alliance",
     "type": "Industry Assoc", "scope": "Global", "founded_year": 2018, "website": "https://www.o-ran.org", "region": "Global"},
    {"name": "TM Forum", "full_name": "TeleManagement Forum",
     "type": "Industry Assoc", "scope": "Global", "founded_year": 1988, "website": "https://www.tmforum.org", "region": "Global"},
    {"name": "Broadband Forum", "full_name": "Broadband Forum (BBF)",
     "type": "Standards", "scope": "Global", "founded_year": 1994, "website": "https://www.broadband-forum.org", "region": "Global"},
    {"name": "DVB Project", "full_name": "Digital Video Broadcasting Project",
     "type": "Standards", "scope": "Global", "founded_year": 1993, "website": "https://www.dvb.org", "region": "Global"},
    {"name": "ATSC", "full_name": "Advanced Television Systems Committee",
     "type": "Standards", "scope": "Regional", "founded_year": 1982, "website": "https://www.atsc.org", "region": "Americas"},
    {"name": "Alliance for Open Media", "full_name": "Alliance for Open Media (AOM)",
     "type": "Industry Assoc", "scope": "Global", "founded_year": 2015, "website": "https://aomedia.org", "region": "Global"},
    {"name": "SMPTE", "full_name": "Society of Motion Picture and Television Engineers",
     "type": "Standards", "scope": "Global", "founded_year": 1916, "website": "https://www.smpte.org", "region": "Global"},
]

STANDARDS = [
    # 3GPP Release Chain
    {"name": "3GPP Release 15", "identifier": "Rel-15", "issuing_body": "3GPP", "domain": "RAN/Core",
     "status": "Frozen", "published_date": "2018-06-13",
     "description": "First complete 5G NR specification, defines NSA (Non-Standalone) and SA (Standalone) modes, eMBB use case."},
    {"name": "3GPP Release 16", "identifier": "Rel-16", "issuing_body": "3GPP", "domain": "RAN/Core",
     "status": "Frozen", "published_date": "2020-06-25",
     "description": "5G for verticals: URLLC enhancements, V2X (vehicle-to-everything), IIoT, NR-U (unlicensed spectrum)."},
    {"name": "3GPP Release 17", "identifier": "Rel-17", "issuing_body": "3GPP", "domain": "RAN/Core",
     "status": "Frozen", "published_date": "2022-06-17",
     "description": "Enhanced 5G features: RedCap (Reduced Capability), NTN (Non-Terrestrial Networks), 5G multicast/broadcast."},
    {"name": "3GPP Release 18", "identifier": "Rel-18", "issuing_body": "3GPP", "domain": "RAN/Core",
     "status": "Frozen", "published_date": "2024-06-14",
     "description": "5G-Advanced: AI/ML for RAN, XR (Extended Reality) services, enhanced energy efficiency, network slicing improvements."},
    {"name": "3GPP Release 19", "identifier": "Rel-19", "issuing_body": "3GPP", "domain": "RAN/Core",
     "status": "Draft", "published_date": "2026-06-01",
     "description": "Continued 5G-Advanced evolution with early 6G preparatory research and further AI/ML integration."},

    # 3GPP Key Technical Specs
    {"name": "TS 38.101", "identifier": "TS 38.101", "issuing_body": "3GPP", "domain": "RAN",
     "status": "Stable", "published_date": "2018-06-13",
     "description": "NR; User Equipment (UE) radio transmission and reception for 5G New Radio."},
    {"name": "TS 38.300", "identifier": "TS 38.300", "issuing_body": "3GPP", "domain": "RAN",
     "status": "Stable", "published_date": "2018-06-13",
     "description": "NR; NR and NG-RAN Overall Description — defines the 5G radio architecture."},
    {"name": "TS 23.501", "identifier": "TS 23.501", "issuing_body": "3GPP", "domain": "Core",
     "status": "Stable", "published_date": "2018-06-13",
     "description": "System Architecture for the 5G System (5GS) — defines the service-based architecture."},
    {"name": "TS 23.502", "identifier": "TS 23.502", "issuing_body": "3GPP", "domain": "Core",
     "status": "Stable", "published_date": "2018-06-13",
     "description": "Procedures for the 5G System (5GS) — registration, session management, and handover procedures."},
    {"name": "TS 33.501", "identifier": "TS 33.501", "issuing_body": "3GPP", "domain": "Security",
     "status": "Stable", "published_date": "2018-06-13",
     "description": "Security architecture and procedures for 5G System — authentication, encryption, and integrity protection."},

    # ITU Standards
    {"name": "IMT-2020", "identifier": "IMT-2020", "issuing_body": "ITU-R", "domain": "RAN",
     "status": "Stable", "published_date": "2017-02-23",
     "description": "Framework and overall objectives for IMT-2020 (5G) defining peak data rates, latency, and spectrum requirements."},
    {"name": "IMT-2030", "identifier": "IMT-2030", "issuing_body": "ITU-R", "domain": "RAN",
     "status": "Draft", "published_date": "2023-11-01",
     "description": "Framework and overall objectives for IMT-2030 (6G) targeting terabit speeds and sub-millisecond latency."},
    {"name": "G.709", "identifier": "G.709", "issuing_body": "ITU-T", "domain": "Transport",
     "status": "Stable", "published_date": "2020-07-01",
     "description": "Interfaces for the Optical Transport Network (OTN) — defines framing and multiplexing for 100G+ optical transport."},
    {"name": "H.265/HEVC", "identifier": "H.265", "issuing_body": "ITU-T", "domain": "Media",
     "status": "Stable", "published_date": "2013-04-13",
     "description": "High Efficiency Video Coding — 50% better compression than H.264 at same quality, widely used in streaming and broadcast."},
    {"name": "H.266/VVC", "identifier": "H.266", "issuing_body": "ITU-T", "domain": "Media",
     "status": "Stable", "published_date": "2020-08-04",
     "description": "Versatile Video Coding — 50% better compression than HEVC, targeting 4K/8K and 360° video streaming."},

    # ETSI Standards
    {"name": "ETSI NFV", "identifier": "GS NFV 001", "issuing_body": "ETSI", "domain": "Core",
     "status": "Stable", "published_date": "2013-10-01",
     "description": "Network Functions Virtualization — use cases and framework for virtualizing network functions on COTS hardware."},
    {"name": "ETSI MEC", "identifier": "GS MEC 001", "issuing_body": "ETSI", "domain": "Edge",
     "status": "Stable", "published_date": "2016-03-01",
     "description": "Multi-access Edge Computing — architecture for hosting applications at the network edge close to users."},

    # O-RAN Alliance
    {"name": "O-RAN WG1", "identifier": "O-RAN.WG1", "issuing_body": "O-RAN Alliance", "domain": "RAN",
     "status": "Stable", "published_date": "2020-01-01",
     "description": "Use Cases and Overall Architecture for Open RAN — defines O-RAN system architecture and use cases."},
    {"name": "O-RAN WG4", "identifier": "O-RAN.WG4", "issuing_body": "O-RAN Alliance", "domain": "RAN",
     "status": "Stable", "published_date": "2020-07-01",
     "description": "Open Fronthaul Interfaces for O-RAN — standardizes the interface between O-DU and O-RU."},
    {"name": "O-RAN WG6", "identifier": "O-RAN.WG6", "issuing_body": "O-RAN Alliance", "domain": "RAN",
     "status": "Stable", "published_date": "2021-03-01",
     "description": "Cloudification and O-Cloud for Open RAN — defines cloud infrastructure requirements for O-RAN deployments."},

    # Media / Internet Standards
    {"name": "MPEG-DASH", "identifier": "ISO/IEC 23009-1", "issuing_body": "IETF", "domain": "Media",
     "status": "Stable", "published_date": "2012-04-01",
     "description": "Dynamic Adaptive Streaming over HTTP — standard for adaptive bitrate video delivery over the internet."},
    {"name": "HLS", "identifier": "RFC 8216", "issuing_body": "IETF", "domain": "Media",
     "status": "Stable", "published_date": "2017-08-01",
     "description": "HTTP Live Streaming — Apple's adaptive streaming protocol, dominant in mobile video delivery."},
    {"name": "AV1", "identifier": "AV1", "issuing_body": "Alliance for Open Media", "domain": "Media",
     "status": "Stable", "published_date": "2018-06-28",
     "description": "Royalty-free video coding format developed for internet delivery — 30% better efficiency than HEVC."},
    {"name": "ATSC 3.0", "identifier": "A/300", "issuing_body": "ATSC", "domain": "Media",
     "status": "Stable", "published_date": "2017-09-07",
     "description": "Next Generation TV broadcast standard combining over-the-air TV with IP-based interactive services."},
    {"name": "SMPTE ST 2110", "identifier": "ST 2110", "issuing_body": "SMPTE", "domain": "Media",
     "status": "Stable", "published_date": "2017-11-01",
     "description": "Professional Media Over IP Networks — standard for uncompressed video and audio transport over IP."},
    {"name": "IEEE 802.11ax", "identifier": "IEEE 802.11ax", "issuing_body": "IEEE", "domain": "RAN",
     "status": "Stable", "published_date": "2021-02-26",
     "description": "Wi-Fi 6/6E — High-efficiency WLAN standard with OFDMA and MU-MIMO for dense deployments."},
    {"name": "IEEE 802.3", "identifier": "IEEE 802.3", "issuing_body": "IEEE", "domain": "Transport",
     "status": "Stable", "published_date": "2018-06-14",
     "description": "Ethernet standard defining wired LAN connections from 1Mbps to 400Gbps."},
    {"name": "DOCSIS 3.1", "identifier": "DOCSIS 3.1", "issuing_body": "Broadband Forum", "domain": "Transport",
     "status": "Stable", "published_date": "2013-10-01",
     "description": "Data Over Cable Service Interface Specifications 3.1 — enables multi-gigabit broadband over HFC cable networks."},
]
