TECHNOLOGIES = [
    # RAN
    {"name": "5G NR", "category": "RAN", "generation": "5G",
     "description": "5G New Radio — the air interface standard for 5G, operating from sub-1GHz to mmWave frequencies."},
    {"name": "Massive MIMO", "category": "RAN", "generation": "5G",
     "description": "Multiple-Input Multiple-Output with large antenna arrays (64-256+ elements) enabling spatial multiplexing and beamforming."},
    {"name": "Beamforming", "category": "RAN", "generation": "5G",
     "description": "Signal processing technique directing radio energy toward specific users, increasing spectral efficiency and coverage."},
    {"name": "mmWave", "category": "RAN", "generation": "5G",
     "description": "Millimeter wave spectrum (24-100 GHz) enabling multi-gigabit 5G speeds over short distances."},
    {"name": "Sub-6GHz 5G", "category": "RAN", "generation": "5G",
     "description": "5G deployment in sub-6GHz bands providing wider coverage with moderate speed improvements over 4G."},
    {"name": "O-RAN", "category": "RAN", "generation": "5G",
     "description": "Open Radio Access Network — disaggregated RAN architecture with open interfaces enabling multi-vendor deployments."},
    {"name": "vRAN", "category": "RAN", "generation": "5G",
     "description": "Virtualized RAN — software-defined baseband processing running on COTS servers instead of proprietary hardware."},
    {"name": "Cloud RAN", "category": "RAN", "generation": "5G",
     "description": "Centralized/Cooperative RAN where baseband processing is pooled in a central cloud data center."},
    {"name": "NB-IoT", "category": "RAN", "generation": "4G/5G",
     "description": "Narrowband IoT — low-power wide-area technology for IoT devices requiring infrequent small data transmissions."},
    {"name": "LTE-M", "category": "RAN", "generation": "4G",
     "description": "LTE for Machines — Cat-M1 standard enabling voice and data for mobile IoT devices with low power consumption."},
    {"name": "URLLC", "category": "RAN", "generation": "5G",
     "description": "Ultra-Reliable Low Latency Communications — 5G service category targeting <1ms latency for industrial automation and V2X."},
    {"name": "eMBB", "category": "RAN", "generation": "5G",
     "description": "Enhanced Mobile Broadband — 5G service category for high-data-rate applications like AR/VR and 4K streaming."},
    {"name": "4G LTE", "category": "RAN", "generation": "4G",
     "description": "Long-Term Evolution — dominant mobile broadband standard providing peak speeds of 100Mbps-1Gbps."},

    # Core Network
    {"name": "5G Core", "category": "Core", "generation": "5G",
     "description": "Cloud-native 5G core network (5GC) based on service-based architecture with microservices and REST APIs."},
    {"name": "Network Slicing", "category": "Core", "generation": "5G",
     "description": "Creating multiple virtual networks on shared physical infrastructure, each with dedicated SLA characteristics."},
    {"name": "Network Function Virtualization", "category": "Core", "generation": "4G/5G",
     "description": "NFV — virtualizing network functions onto software running on COTS servers, eliminating proprietary hardware."},
    {"name": "Service Based Architecture", "category": "Core", "generation": "5G",
     "description": "SBA — 5G core design where network functions expose REST/HTTP APIs and communicate via a service mesh."},
    {"name": "User Plane Function", "category": "Core", "generation": "5G",
     "description": "UPF — the data plane anchor in 5GC responsible for packet routing, forwarding, and QoS enforcement."},
    {"name": "SD-WAN", "category": "Core", "generation": "4G/5G",
     "description": "Software-Defined WAN — abstracting WAN connectivity from hardware to enable application-aware routing."},
    {"name": "SASE", "category": "Core", "generation": "5G",
     "description": "Secure Access Service Edge — converging networking and security in a cloud-delivered architecture."},
    {"name": "Zero Trust Network Access", "category": "Core", "generation": "5G",
     "description": "ZTNA — security model eliminating implicit trust, requiring continuous verification for all users and devices."},

    # Edge & Cloud
    {"name": "Multi-access Edge Computing", "category": "Edge", "generation": "5G",
     "description": "MEC — ETSI standard for hosting applications at the network edge, enabling ultra-low latency services."},
    {"name": "Private 5G", "category": "Edge", "generation": "5G",
     "description": "Dedicated 5G networks for enterprises, factories, and campuses providing high-speed low-latency connectivity."},
    {"name": "Network as Code", "category": "Edge", "generation": "5G",
     "description": "Programmable network APIs exposing 5G capabilities to developers for application-aware networking."},
    {"name": "Telco Cloud", "category": "Edge", "generation": "5G",
     "description": "Cloud infrastructure running telecom workloads (CNFs) using Kubernetes and cloud-native principles."},
    {"name": "Kubernetes for CNFs", "category": "Edge", "generation": "5G",
     "description": "Kubernetes-based orchestration for Cloud-Native Network Functions replacing VMs in telecom infrastructure."},

    # AI/ML
    {"name": "RAN Intelligent Controller", "category": "AI/ML", "generation": "5G",
     "description": "RIC — O-RAN component providing real-time (near-RT) and non-real-time control over RAN parameters via AI/ML."},
    {"name": "xApps and rApps", "category": "AI/ML", "generation": "5G",
     "description": "Microservice applications running on the RIC, enabling third-party RAN optimization algorithms."},
    {"name": "AIOps for Networks", "category": "AI/ML", "generation": "5G",
     "description": "AI-driven network operations automating fault detection, root cause analysis, and capacity planning."},
    {"name": "Predictive Maintenance", "category": "AI/ML", "generation": "5G",
     "description": "ML models predicting network equipment failures before they occur, reducing OPEX and outages."},
    {"name": "LLM-assisted OSS/BSS", "category": "AI/ML", "generation": "5G",
     "description": "Large language model integration in operations support and business support systems for automation."},

    # Transport
    {"name": "Optical Transport Network", "category": "Transport", "generation": "Fixed",
     "description": "OTN — ITU-T G.709 standard for multiplexing, switching, and monitoring optical channels at 10G-800G."},
    {"name": "DWDM", "category": "Transport", "generation": "Fixed",
     "description": "Dense Wavelength Division Multiplexing — transmitting multiple optical signals on a single fiber using different wavelengths."},
    {"name": "Coherent Optics", "category": "Transport", "generation": "Fixed",
     "description": "Modulation technology enabling 100G-800G+ transmission per wavelength using advanced DSP chips."},
    {"name": "Segment Routing", "category": "Transport", "generation": "Fixed",
     "description": "Traffic engineering technique embedding forwarding instructions in packet headers, simplifying MPLS networks."},
    {"name": "SRv6", "category": "Transport", "generation": "Fixed",
     "description": "Segment Routing over IPv6 — extends SR to IPv6, enabling flexible traffic engineering and network slicing in IP networks."},
    {"name": "MPLS", "category": "Transport", "generation": "Fixed",
     "description": "Multiprotocol Label Switching — packet forwarding technology using labels for fast switching in carrier networks."},

    # Media
    {"name": "H.264/AVC", "category": "Media", "generation": "Broadcast",
     "description": "Advanced Video Coding — the most widely deployed video compression standard, used in streaming, broadcast, and recording."},
    {"name": "H.265/HEVC", "category": "Media", "generation": "Broadcast",
     "description": "High Efficiency Video Coding — 50% better compression than H.264, used in 4K broadcast and streaming."},
    {"name": "H.266/VVC", "category": "Media", "generation": "Broadcast",
     "description": "Versatile Video Coding — 50% better than HEVC, targeting 4K/8K and 360-degree video applications."},
    {"name": "AV1 Codec", "category": "Media", "generation": "Streaming",
     "description": "Open, royalty-free video codec by Alliance for Open Media — 30% better than HEVC, used by Netflix, YouTube, and Google."},
    {"name": "Adaptive Bitrate Streaming", "category": "Media", "generation": "Streaming",
     "description": "ABR — dynamically adjusting video quality based on available bandwidth, used in HLS and MPEG-DASH."},
    {"name": "Content Delivery Network", "category": "Media", "generation": "Streaming",
     "description": "CDN — geographically distributed servers caching content close to users, reducing latency and origin load."},
    {"name": "IPTV", "category": "Media", "generation": "Broadcast",
     "description": "Internet Protocol Television — delivering TV content over managed IP networks with QoS guarantees."},
    {"name": "OTT Streaming", "category": "Media", "generation": "Streaming",
     "description": "Over-the-Top streaming — delivering video directly to consumers via internet, bypassing traditional broadcast."},
    {"name": "FAST Channels", "category": "Media", "generation": "Streaming",
     "description": "Free Ad-Supported Streaming TV — linear TV channels delivered via internet, monetized through advertising."},
]

MARKETS = [
    {"name": "Enterprise 5G", "segment": "Connectivity", "geography": "Global",
     "size_usd_bn": 8.5, "size_year": 2023, "cagr_pct": 32.5, "forecast_year": 2028,
     "description": "5G connectivity solutions for large enterprises including private networks and 5G-enabled IoT."},
    {"name": "Private 5G Networks", "segment": "Connectivity", "geography": "Global",
     "size_usd_bn": 4.7, "size_year": 2023, "cagr_pct": 45.0, "forecast_year": 2028,
     "description": "Dedicated 5G networks deployed for factories, ports, campuses, and critical infrastructure."},
    {"name": "Video Streaming", "segment": "Media", "geography": "Global",
     "size_usd_bn": 125.0, "size_year": 2023, "cagr_pct": 18.5, "forecast_year": 2028,
     "description": "Subscription and ad-supported video streaming services including SVOD, AVOD, and FAST."},
    {"name": "Network Slicing Market", "segment": "Connectivity", "geography": "Global",
     "size_usd_bn": 1.2, "size_year": 2023, "cagr_pct": 58.0, "forecast_year": 2028,
     "description": "Commercial network slicing services offered by operators for vertical industry use cases."},
    {"name": "Open RAN Market", "segment": "Connectivity", "geography": "Global",
     "size_usd_bn": 6.5, "size_year": 2023, "cagr_pct": 40.0, "forecast_year": 2028,
     "description": "Disaggregated open RAN equipment and software market including O-RU, O-DU, O-CU, and RIC."},
    {"name": "Telecom Edge Computing", "segment": "Cloud", "geography": "Global",
     "size_usd_bn": 12.0, "size_year": 2023, "cagr_pct": 28.0, "forecast_year": 2028,
     "description": "Edge compute hosted at telecom network nodes enabling low-latency enterprise and consumer applications."},
    {"name": "Satellite Broadband", "segment": "Connectivity", "geography": "Global",
     "size_usd_bn": 9.8, "size_year": 2023, "cagr_pct": 25.0, "forecast_year": 2028,
     "description": "Internet access via satellite including LEO constellations (Starlink, OneWeb) and GEO HTS services."},
]
